[package]
name = "logisticRegression"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18"
rand = "0.7.3"
csv = "1.1.3"
serde_derive = "1.0.116"
serde = "1.0.116"